application: whats-up-mon
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /check
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app
  login: required
  secure: always